SET SERVEROUTPUT ON 
--1--
  DECLARE
    v LONG := 'HOLA MUNDO';
  BEGIN
    DBMS_OUTPUT.PUT_LINE(v);
  END;




--2--

  DECLARE
    v CENTROS.ID%TYPE;
  
  BEGIN  
    select ID into v from CENTROS WHERE ID = 4; -- MAX(ID)--
    
    if SQL%FOUND THEN
      DBMS_OUTPUT.PUT_LINE('EL ID MAXIMO ES '||v);
    end if; 
       
  EXCEPTION  
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('No existe '||v);
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO'||v);
  
  
  
   
  END;
  
  --NO DEVUELVE NADA YA QUE NO TENEMOS DATOS INTRODUCIDOS CENTROS EN LA TABLA CENTROS--
  
--3--
  
  INSERT INTO CENTROS(NOMBRE,CALLE,NUMERO,CP,CIUDAD,PROVINCIA,TELEFONO)
  VALUES ('P','A',30,'T','Y','U','I');
  
  SELECT * FROM CENTROS;
  DESC CENTROS;

  /*NO HACE FALTA INTRODUCIR ID YA QUE TENEMOS UNA COLUMNA AUTOINCREMETAL CON ALWAYS
  (NO PERMITE LA INTRODUCCION MANUAL DE LA COLUMNA EN CUESTION)*/



--4--


--5--
  
  